project:
  type: website

website:
  title: "Welcome"
  sidebar:
    style: "docked"
    search: true

    contents:
      - index.qmd
      - blog.qmd
      - section: "Notes and exercises"
        contents:
          - base/probability/probability.qmd
          - base/jax/simple_jax.qmd
  
  #navbar:
  #  left:
  #    - href: index.qmd
  #      text: Home
  #    - about.qmd
  #    - about.qmd
  #    - about.qmd
  #    - about.qmd
  page-footer: 
    center: "Copyright 2022, David Yu, made with [Quarto](https://quarto.org/)" 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

